### ISSUE TITLE
does not seem to convert pytorch datasets correctly

### ISSUE THREAD

**Issue by murphyk** [BirkhoffG/jax-dataloader#1]
Consider this example
```
import jax_dataloader.core as jdl
from torch.utils.data import DataLoader, TensorDataset
from torchvision.transforms import ToTensor
from torchvision.datasets import MNIST
train_ds = MNIST('/tmp/mnist/', download=True, transform=ToTensor())

train_loader = jdl.DataLoader(train_ds, 'pytorch', batch_size=5, shuffle=False, drop_last=False)
train_iter = iter(train_loader)
nbatches = len(train_iter)
for b in range(1): #nbatches):
    Xtr, Ytr = next(train_iter)
    print(b, Xtr.shape, Ytr.shape, type(Xtr), type(Ytr))
    print(type(Xtr[0]), Xtr[0].shape, Ytr[0].shape)
```
This returns
```
0 (5,) (5,) <class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'torch.Tensor'> torch.Size([1, 28, 28]) ()
```
so the elements within the batch are still pytorch tensors, not numpy arrays.

**Comment by BirkhoffG** [comment]
Hi @murphyk 

Thanks for the question and the feedback to the library. 

The `jdl.DataLoader` takes `jdl.Dataset` as input (not a pytorch Dataset). I am working to integrate the use of both PyTorch and huggingface datasets into this library.

**Comment by murphyk** [comment]
Oh, I see. So the dataset is `jdl.Dataset` but the backend dataloader can be jax, pytorch, or tf?  
But if I want to use a pytorch dataset, I need to first convert it to numpy? What's the best way to do this?

**Comment by BirkhoffG** [comment]
Hi @murphyk 

Thanks for your questions and suggestions. For pytorch dataset, here is what I would like to do:

```python
import jax_dataloader.core as jdl
from torch.utils.data import DataLoader, TensorDataset
from torchvision.transforms import ToTensor
from torchvision.datasets import MNIST

class ToNumpy(object):
  def __call__(self, pic):
    return np.array(pic, dtype=float)

train_ds = = MNIST('/tmp/mnist/', download=True, transform=ToNumpy(), train=True)
train_dl = jdl.Dataloader(train_ds, 'pytorch', batch_size=5, shuffle=True) # Using 'pytorch' as the backend is a must for now

imgs, label = next(iter(train_dl))
```

Note that currently, the `'jax'` data loader is not compatible with the PyTorch dataset. If you want to use pytorch dataset, you should specify `'pytorch'` when using the `jdl.Dataloader`.

I am also adding support for the Huggingface datasets, which seems to work more naturally for jax. Documentations is coming up.
