### ISSUE TITLE
Custom Jax dataset does not work

### ISSUE THREAD

**Issue by gabrielvc** [BirkhoffG/jax-dataloader#10]
Hi,

I'm trying to create a base Dataset (in the pytorch style, but from the default jax_dataloader) but the dataloader crashes if torch is not installed. 
This is due to the function `_dispatch_dataset_and_backend` that has the following condition:
`if isinstance(dataset, torch_data.Dataset)...` but as torch_data = None, this crashes.

**Comment by BirkhoffG** [comment]
Hi, have you tried our latest version by `pip install git+https://github.com/BirkhoffG/jax-dataloader.git`.

I believe this duplicates #6, which has already been fixed in our current main branch.

**Comment by gabrielvc** [comment]
Thanks, Indeed it is. It seems to work now, thanks.
