### ISSUE TITLE
Slow Loading speed

### ISSUE THREAD

**Issue by Impure-King** [BirkhoffG/jax-dataloader#22]
Hey, just want to say that I have been a huge fan of your work. I just jax_dataloader quite often in my workflow, but I have noticed that the dataloader slows down my training loop by 5 seconds every 10 epochs (compared to tensorflow's numpy iterator). I am not using prefetch on the numpy iterator, so do let me know if you have anticipated this before.

P.S. My training loop is quite ordinary (but my models are rn being developed by an internal library, so I can't disclose the code), so I know that the dataloading speed is the problem.

**Comment by BirkhoffG** [comment]
Hi @Impure-King, can you test using the latest code in the `main` branch? 

You can install the latest library by running this:

```python
pip install git+https://github.com/BirkhoffG/jax-dataloader.git
```

Let me know if this improves the loading. If not, could you let me know your environments, including jax version, GPU or CPU, etc?

**Comment by Impure-King** [comment]
Thanks for the quick reply! The last code in the ``main`` branch fixes the problem and even offers a ~6 sec speed up compared to ``tensorflow``'s solutions. Thanks so much and I look forward to the new release.
