### ISSUE TITLE
DataLoaderJAX length?

### ISSUE THREAD

**Issue by allen-adastra** [BirkhoffG/jax-dataloader#33]
Hello!

I'm curious about the second term of `__len__` for `DataloaderJAX`?

```
    def __len__(self):
        return len(self.indices) // self.batch_size + int(not self.drop_last)
```

In the full-batch case, I'd expect a length of 1 for the dataloader, but if `drop_last=False`, I get back two. Is this an edge-case or am I misunderstanding the definition of the length?

Perhaps we need to have instead:
```
    def __len__(self):
        n_full_batches = len(self.indices) // self.batch_size
        incomplete_last_batch = (len(self.indices) % self.batch_size)) != 0
        if incomplete_last_batch:
            return n_full_batches + int(not self.drop_last)
        else:
            return n_full_batches
```

**Comment by BirkhoffG** [comment]
Thanks @allen-adastra. Looking into this...
