### ISSUE TITLE
Set up random seed for dataloader

### ISSUE THREAD

**Issue by DSilva27** [BirkhoffG/jax-dataloader#35]
Hi,

I recently started using your dataloader for one of my projects. How can I set a random seed for the shuffle operation?

**Comment by BirkhoffG** [comment]
Hi @DSilva27, thank you for your questions. The latest `jax-dataloader` supports setting global seed as:

```python
import jax_dataloader as jdl

jdl.manual_seed(1234) # set the global seed to 1234
```

This function provides a flexible way to set global seed, and works for all backends. Hope this will help.
